#Using a series of print statements to write my initials which is ONO (Onyedikachi Nnenna Onah)
print(" OOOOO   N        N   OOOOO ")
print("O     O  NN       N  O     O")
print("O     0  N N      N  O     O")
print("O     O  N  N     N  O     O")
print("O     O  N   N    N  O     O")
print("O     O  N    N   N  O     O")
print("O     O  N     N  N  O     O")
print("O     O  N      N N  O     O")
print("O     O  N       NN  O     O")
print(" OOOOO   N        N   OOOOO ")